### ISSUE TITLE
OHIF viewer issue with cornerstoneWADOImageLoader v4.1.0 and above

### ISSUE THREAD

**Issue by abymmathew-mli** [microsoft/dicom-ohif#10]
### Synopsis

OHIF viewer doesn't accept responses from Azure Dicom Service for WADO GET requests. As per spec, the main response should be multipart.

multipart/related; type=application/dicom; boundary={MessageBoundary} 
(ref: https://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html)

### Powershell code snippet

`$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.61"
Invoke-WebRequest -UseBasicParsing -Uri "https://ohifintegration-xx.dicom.azurehealthcareapis.com/v1/studies/1.2.826.0.1.3680043.8.498.13230779778012324449356534479549187420/series/1.2.826.0.1.3680043.8.498.77033797676425927098669402985243398207/instances/1.2.826.0.1.3680043.8.498.13273713909719068980354078852867170114/frames/1" `
-WebSession $session `
-Headers @{
"authority"="ohifintegration-xx.dicom.azurehealthcareapis.com"
  "method"="GET"
  "path"="/v1/studies/1.2.826.0.1.3680043.8.498.13230779778012324449356534479549187420/series/1.2.826.0.1.3680043.8.498.77033797676425927098669402985243398207/instances/1.2.826.0.1.3680043.8.498.13273713909719068980354078852867170114/frames/1"
  "scheme"="https"
  "accept"="multipart/related; type=`"application/octet-stream`"; transfer-syntax=*"
  "accept-encoding"="gzip, deflate, br"
  "accept-language"="en-US,en;q=0.9"
  "authorization"="Bearer xx"
  "origin"="https://mlioihfintegration01.z19.web.core.windows.net"
  "referer"="https://mlioihfintegration01.z19.web.core.windows.net/"
  "sec-ch-ua"="`"Not_A Brand`";v=`"99`", `"Microsoft Edge`";v=`"109`", `"Chromium`";v=`"109`""
  "sec-ch-ua-mobile"="?0"
  "sec-ch-ua-platform"="`"Windows`""
  "sec-fetch-dest"="empty"
  "sec-fetch-mode"="cors"
  "sec-fetch-site"="cross-site"
} | Select -ExpandProperty Headers`

### Analysis

The above snipet with  **"accept"="multipart/related; type=`"application/octet-stream`"; transfer-syntax=*"** will return,
**Content-Type: multipart/related; boundary=38426a24-c3ad-471a-8c89-c5d9210e3eaa**

_This is acceptable by OHIF since the loader looks for the multipart/related in the header of the response._

However with **"accept"="multipart/related; type=application/octet-stream; transfer-syntax=*"** will return,
**Content-Type: application/dicom; transfer-syntax=1.2.840.10008.1.2.1**

_This is not acceptable by OHIF since the loader looks for the multipart/related in the header of the response._

The acceptable request is generated by cornerstoneWADOImageLoader v4.1.0 in OHIF and v4.1.1 or above will produce the unaccepted header format.

### Note 

- https://github.com/cornerstonejs/cornerstoneWADOImageLoader/commit/37b076d336951d3added50b352c4f87b78778f25, is the change log of cornerstoneWADOImageLoader between v4.1.0 and v4.1.1
- Any "xx" in the snippet was part of the obfuscation of private content.

**Comment by smithago** [comment]
Hello, this repo, just shows how to integrate Azure DICOM service with OHIF. This looks like an issue with OHIF code, I would recommend to log a bug on the OHIF repo https://github.com/OHIF/Viewers

**Comment by abymmathew-mli** [comment]
Thanks, Smitha, I will log in with Azure Dicom service since the spec states that multipart/related is required.

multipart/related; type=application/dicom; boundary={MessageBoundary}
(ref: https://dicom.nema.org/dicom/2013/output/chtml/part18/sect_6.5.html)
