### ISSUE TITLE
Request does not match the redirect URIs

### ISSUE THREAD

**Issue by luistelmocosta** [microsoft/dicom-ohif#8]
Hello, 

I followed the step by step tutorial in the README.md and I keep getting the following error. I added the callback URL to the app Authentication but it did not work.

I also followed [this article](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-redirect-uri-mismatch) and added the /silent.html callback but no success. 

![image](https://user-images.githubusercontent.com/7799750/186151440-86e5777c-ec80-476a-8de5-cce2c4a84f04.png)

Any suggestion on how to solve this?

Kind regards, 
Luís

**Comment by smithago** [comment]
Hey, this is another issue with OHIF, to make it work configure your browser to block redirects and pops from this url.

**Comment by lenisha** [comment]
same issue keeps trying silent refresh

**Comment by smithago** [comment]
The repo is updated to latest OHIF viewer. Install the portal from the repo again and issue should be resolved
